create table tb_order (id int8 generated by default as identity, address varchar(50), latitude float8, longitude float8, moment timestamp not null, status int4 not null, primary key (id));
create table tb_order_product (order_id int8 not null, product_id int8 not null, primary key (order_id, product_id));
create table tb_product (id int8 generated by default as identity, description varchar(130), image_uri varchar(255) not null, name varchar(30) not null, price float8, primary key (id));
alter table if exists tb_product add constraint UK_lovy3681ry0dl5ox28r6679x6 unique (name);
alter table if exists tb_order_product add constraint FKsu03ywlcvyqg5y78qey2q25lc foreign key (product_id) references tb_product;
alter table if exists tb_order_product add constraint FK40anaevs16kmc2tbh7wc511fq foreign key (order_id) references tb_order;
